import type { Branch, InventoryRecord, PriceRule, Product } from "@/lib/domain/types";

export const branches: Branch[] = [
  { id: "centro", name: "Centro", city: "Ciudad de México" },
  { id: "norte", name: "Norte", city: "Naucalpan" },
  { id: "sur", name: "Sur", city: "Coyoacán" },
];

export const products: Product[] = [
  {
    id: "product-aurora-55",
    slug: "smart-tv-aurora-55",
    name: "Smart TV Aurora 55\" 4K",
    brand: "Aurora",
    category: "Electrónica",
    description: "Panel 4K con HDR y sistema de entretenimiento integrado.",
    tags: ["4K", "HDR", "55 pulgadas"],
    tone: "teal",
    variant: { id: "variant-aurora-55", sku: "AUR-55-4K", label: "55 pulgadas", listPrice: 12999, currency: "MXN" },
  },
  {
    id: "product-nova-headphones",
    slug: "audifonos-nova-anc",
    name: "Audífonos Nova ANC",
    brand: "Nova",
    category: "Electrónica",
    description: "Cancelación adaptativa de ruido y 32 horas de batería.",
    tags: ["Bluetooth", "ANC", "Audio"],
    tone: "blue",
    variant: { id: "variant-nova-anc", sku: "NOV-ANC-01", label: "Grafito", listPrice: 2899, currency: "MXN" },
  },
  {
    id: "product-lumen-lamp",
    slug: "lampara-lumen-mesa",
    name: "Lámpara Lumen de mesa",
    brand: "Lumen",
    category: "Hogar",
    description: "Iluminación cálida regulable para sala o escritorio.",
    tags: ["LED", "Regulable", "Hogar"],
    tone: "orange",
    variant: { id: "variant-lumen-lamp", sku: "LUM-DESK-01", label: "Arena", listPrice: 1499, currency: "MXN" },
  },
  {
    id: "product-kinetic-shoes",
    slug: "tenis-kinetic-run",
    name: "Tenis Kinetic Run",
    brand: "Kinetic",
    category: "Deportes",
    description: "Amortiguación reactiva para entrenamiento diario.",
    tags: ["Running", "Ligero", "Unisex"],
    tone: "lime",
    variant: { id: "variant-kinetic-26", sku: "KIN-RUN-26", label: "Talla 26", listPrice: 2199, currency: "MXN" },
  },
  {
    id: "product-atelier-chair",
    slug: "silla-atelier",
    name: "Silla Atelier",
    brand: "Atelier",
    category: "Hogar",
    description: "Silla de acento con estructura de madera certificada.",
    tags: ["Madera", "Diseño", "Sala"],
    tone: "pink",
    variant: { id: "variant-atelier-chair", sku: "ATL-CHR-01", label: "Terracota", listPrice: 4699, currency: "MXN" },
  },
  {
    id: "product-vertex-watch",
    slug: "reloj-vertex-fit",
    name: "Reloj Vertex Fit",
    brand: "Vertex",
    category: "Deportes",
    description: "Métricas de actividad, sueño y recuperación.",
    tags: ["GPS", "Salud", "Resistente"],
    tone: "slate",
    variant: { id: "variant-vertex-fit", sku: "VTX-FIT-02", label: "Negro", listPrice: 3499, currency: "MXN" },
  },
];

export const priceRules: PriceRule[] = [
  {
    id: "rule-home-week",
    name: "Semana de hogar",
    status: "PUBLISHED",
    priority: 20,
    discountType: "PERCENTAGE",
    discountValue: 12,
    startsAt: "2025-01-01T00:00:00.000Z",
    endsAt: "2030-01-01T00:00:00.000Z",
    targets: [{ type: "category", id: "Hogar" }],
  },
  {
    id: "rule-night-sale",
    name: "Venta nocturna",
    status: "PUBLISHED",
    priority: 30,
    discountType: "PERCENTAGE",
    discountValue: 18,
    dailyWindow: { start: "00:00", end: "06:00", timeZone: "America/Mexico_City" },
    targets: [{ type: "category", id: "Electrónica" }],
  },
];

export const inventorySeed: InventoryRecord[] = [
  { variantId: "variant-aurora-55", branchId: "centro", onHand: 1, reservedQuantity: 0, lowStockThreshold: 3 },
  { variantId: "variant-aurora-55", branchId: "norte", onHand: 8, reservedQuantity: 0, lowStockThreshold: 3 },
  { variantId: "variant-aurora-55", branchId: "sur", onHand: 4, reservedQuantity: 0, lowStockThreshold: 3 },
  { variantId: "variant-nova-anc", branchId: "centro", onHand: 18, reservedQuantity: 2, lowStockThreshold: 5 },
  { variantId: "variant-nova-anc", branchId: "norte", onHand: 11, reservedQuantity: 1, lowStockThreshold: 5 },
  { variantId: "variant-nova-anc", branchId: "sur", onHand: 7, reservedQuantity: 0, lowStockThreshold: 5 },
  { variantId: "variant-lumen-lamp", branchId: "centro", onHand: 6, reservedQuantity: 0, lowStockThreshold: 4 },
  { variantId: "variant-lumen-lamp", branchId: "norte", onHand: 3, reservedQuantity: 0, lowStockThreshold: 4 },
  { variantId: "variant-lumen-lamp", branchId: "sur", onHand: 9, reservedQuantity: 0, lowStockThreshold: 4 },
  { variantId: "variant-kinetic-26", branchId: "centro", onHand: 14, reservedQuantity: 1, lowStockThreshold: 5 },
  { variantId: "variant-kinetic-26", branchId: "norte", onHand: 12, reservedQuantity: 0, lowStockThreshold: 5 },
  { variantId: "variant-kinetic-26", branchId: "sur", onHand: 2, reservedQuantity: 0, lowStockThreshold: 5 },
  { variantId: "variant-atelier-chair", branchId: "centro", onHand: 2, reservedQuantity: 0, lowStockThreshold: 2 },
  { variantId: "variant-atelier-chair", branchId: "norte", onHand: 5, reservedQuantity: 1, lowStockThreshold: 2 },
  { variantId: "variant-atelier-chair", branchId: "sur", onHand: 3, reservedQuantity: 0, lowStockThreshold: 2 },
  { variantId: "variant-vertex-fit", branchId: "centro", onHand: 10, reservedQuantity: 0, lowStockThreshold: 5 },
  { variantId: "variant-vertex-fit", branchId: "norte", onHand: 4, reservedQuantity: 0, lowStockThreshold: 5 },
  { variantId: "variant-vertex-fit", branchId: "sur", onHand: 6, reservedQuantity: 1, lowStockThreshold: 5 },
];
